# Generated by Django 5.2.4 on 2026-01-19 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='experience',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
