# Generated by Django 5.2.4 on 2026-01-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_doctorprofile_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='available_days',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='available_from',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='available_to',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='fees',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='specialization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
