# Generated by Django 5.2.4 on 2026-01-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_doctorprofile_available_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='age',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
